spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ac2_database}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:ac2}
  jpa:
    hibernate:
      ddl-auto: validate