services:
  database:
    image: postgres
    container_name: ac2_staging_database
    environment:
      POSTGRES_PASSWORD: ac2
      POSTGRES_DB: ac2_database
    volumes:
      - db-volume:/var/lib/postgresql/data

  api:
    image: joaocamo/ac2:latest
    container_name: ac2_staging_api
    networks:
      - default  # Certifique-se de que está usando a rede adequada
    environment:
      DB_HOST: database
    ports:
      - "8080:8080"

volumes:
  db-volume: