version: '3'

services:
  database:
    image: postgres
    container_name: ac2_staging_database
    environment:
      POSTGRES_PASSWORD: ac2
      POSTGRES_DB: ac2_database
    volumes:
      - db-volume:/var/lib/postgresql/data

  api:
    image: ac2_project
    container_name: ac2_staging_api
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: database
    ports:
      - "8484:8484"
    depends_on:
      - database

volumes:
  db-volume:
